# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore visualization and reporting modules from coverage requirements
ignore:
  - "src/visualizations*.py"
  - "src/plotting.py"
  - "src/perspective_value_viz.py"
  - "src/pipeline/reporting.py"
  - "src/table_generation.py"
  - "src/policy_brief_generator.py"
  - "**/__pycache__/**"
  - "tests/**"

flags:
  unittests:
    paths:
      - src/
    carryforward: true
