# Conda-forge Recipe for vop-poc-nz
# 
# To submit to conda-forge:
# 1. Fork https://github.com/conda-forge/staged-recipes
# 2. Copy this file to recipes/vop-poc-nz/meta.yaml
# 3. Submit a pull request
# 
# Documentation: https://conda-forge.org/docs/maintainer/adding_pkgs.html

{% set name = "vop-poc-nz" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: # Update with actual SHA256 from PyPI after publishing

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - numpy >=1.21
    - pandas >=1.3
    - scipy >=1.7
    - matplotlib-base >=3.4
    - scikit-learn >=1.0
    - statsmodels >=0.13
    - seaborn >=0.11

test:
  imports:
    - vop_poc_nz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/edithatogo/vop_poc_nz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Value of Precision Medicine - Proof of Concept for New Zealand health economics
  description: |
    A comprehensive Python package for health economic analysis with focus on
    cost-effectiveness analysis (CEA), Distributional Cost-Effectiveness Analysis (DCEA),
    value of information analysis, and probabilistic sensitivity analysis.
  doc_url: https://edithatogo.github.io/vop_poc_nz/
  dev_url: https://github.com/edithatogo/vop_poc_nz

extra:
  recipe-maintainers:
    - edithatogo
