"""Immutable domain specifications for health-economic calculations."""

from .base import FrozenDomainModel
from .cea import (
    ArmVectors,
    CostSpec,
    FrictionCostSpec,
    InterventionSpec,
    NumericVector,
    Perspective,
    ProductivityCostMethod,
    TransitionMatrices,
    TransitionMatrix,
)
from .contracts import (
    UNKNOWN_CURRENCY,
    AnalysisSpec,
    DistributionFamily,
    DistributionParameter,
    DistributionSpec,
    MetadataStatus,
    NonFinitePolicy,
    NumericalPolicySpec,
    ParameterSpec,
    ProvenanceSpec,
    RunContextSpec,
    UnitDimension,
    UnitSpec,
)

__all__ = [
    "UNKNOWN_CURRENCY",
    "AnalysisSpec",
    "ArmVectors",
    "CostSpec",
    "DistributionFamily",
    "DistributionParameter",
    "DistributionSpec",
    "FrictionCostSpec",
    "FrozenDomainModel",
    "InterventionSpec",
    "MetadataStatus",
    "NonFinitePolicy",
    "NumericVector",
    "NumericalPolicySpec",
    "ParameterSpec",
    "Perspective",
    "ProductivityCostMethod",
    "ProvenanceSpec",
    "RunContextSpec",
    "TransitionMatrices",
    "TransitionMatrix",
    "UnitDimension",
    "UnitSpec",
]
