#!/usr/bin/env python
"""Validate the systematic software-review ledger and generate its TeX table."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "1.0.0"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate(payload: dict[str, Any]) -> list[str]:
    failures: list[str] = []
    required = {
        "schema_version",
        "review_date",
        "queries",
        "eligibility",
        "flow",
        "included",
        "excluded_full_text",
        "limitations",
    }
    missing = required - payload.keys()
    if missing:
        failures.append(f"missing keys: {sorted(missing)}")
        return failures
    if payload["schema_version"] != SCHEMA_VERSION:
        failures.append("unsupported schema_version")
    flow = payload["flow"]
    if (
        flow["records_retrieved"] - flow["duplicates_removed"]
        != flow["unique_records_screened"]
    ):
        failures.append("deduplication flow is inconsistent")
    if (
        flow["title_description_excluded"] + flow["full_text_assessed"]
        != flow["unique_records_screened"]
    ):
        failures.append("screening flow is inconsistent")
    if flow["full_text_excluded"] + flow["included"] != flow["full_text_assessed"]:
        failures.append("eligibility flow is inconsistent")
    if flow["included"] != len(payload["included"]):
        failures.append("included count does not match records")
    if flow["full_text_excluded"] != len(payload["excluded_full_text"]):
        failures.append("excluded count does not match records")
    required_package = {
        "name",
        "repository",
        "version",
        "language",
        "multi_perspective",
        "dcea",
        "named_directional_vop",
        "evidence",
    }
    for package in payload["included"]:
        if required_package - package.keys():
            failures.append(
                f"incomplete included record: {package.get('name', '<unknown>')}"
            )
    return failures


def _escape(value: str) -> str:
    return value.replace("_", "\\_").replace("&", "\\&")


def generate(root: Path) -> tuple[Path, Path]:
    root = root.resolve()
    review_dir = root / "manuscript" / "software_review"
    ledger = review_dir / "systematic-software-review.json"
    payload = json.loads(ledger.read_text(encoding="utf-8"))
    failures = validate(payload)
    if failures:
        raise ValueError("; ".join(failures))
    rows = [
        "{} & {} & {} & {} & {} \\\\".format(
            _escape(item["name"]),
            _escape(item["language"]),
            _escape(item["multi_perspective"]),
            _escape(item["dcea"]),
            _escape(item["named_directional_vop"]),
        )
        for item in payload["included"]
    ]
    tex = review_dir / "software-comparison.tex"
    tex.write_text(
        "% Generated by scripts/systematic_software_review.py; do not edit.\n"
        "\\newcommand{\\SoftwareComparisonRows}{%\n" + "\n".join(rows) + "\n}\n",
        encoding="utf-8",
        newline="\n",
    )
    manifest = review_dir / "software-review-manifest.json"
    generator = root / "scripts" / "systematic_software_review.py"
    protocol = review_dir / "protocol.md"
    manifest.write_text(
        json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                "review_date": payload["review_date"],
                "priority_claim_supported_within_scope": all(
                    item["named_directional_vop"] == "No"
                    for item in payload["included"]
                ),
                "files": [
                    {"path": path.relative_to(root).as_posix(), "sha256": _sha256(path)}
                    for path in (ledger, protocol, generator, tex)
                ],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return tex, manifest


def verify(root: Path) -> list[str]:
    root = root.resolve()
    manifest = root / "manuscript/software_review/software-review-manifest.json"
    if not manifest.is_file():
        return ["missing software-review manifest"]
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    failures: list[str] = []
    for item in payload.get("files", []):
        path = root / item["path"]
        if not path.is_file() or _sha256(path) != item["sha256"]:
            failures.append(f"stale or missing review artifact: {item['path']}")
    ledger = json.loads(
        (root / "manuscript/software_review/systematic-software-review.json").read_text(
            encoding="utf-8"
        )
    )
    failures.extend(validate(ledger))
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    if args.verify:
        failures = verify(args.root)
        if failures:
            print("\n".join(failures), file=sys.stderr)
            return 1
        print("systematic-software-review: verified")
        return 0
    print(*generate(args.root), sep="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
